[package]
name = "nostr-client-plus"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
anyhow = { workspace = true }
url = "2.5.0"
tokio = {  workspace = true }
tokio-tungstenite = "0.23.0"
futures-util = "0.3.30"
hex = { workspace = true }
k256 = { workspace = true }
nostr-crypto = { workspace = true }
nostr-surreal-db = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
tokio = { version = "1.38.0", features = ["full", "test-util"] }
nostr-surreal-db = { workspace = true }
alloy-primitives = { workspace = true }
